version: '3.9'

services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
    image: myjenkins-master
    container_name: jenkins-master
    restart: on-failure
    networks:
      - jenkins
    environment:
      - SLACK_SECRET_TOKEN=xoxb-7350845836756-7364654862803-T3pT33PXuBh1hpXOtDIB6TZf
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"

  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile-jenkins-agent
    image: jenkins-agent-image
    container_name: jenkins-agent
    ports:
      - "22:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDjh9iBvqQnLaySlV+m3p70CgJJl/XeAA5dGKsbdNrRZTRRGwag6zs2tOG3iMqsMPlEe7UMqvH9/rQnd/vyg124hcpCmdg8AXDnDS/LQuCRhIqMosfwOunDH+SJcDdqyIWsmkRS4Lib8+hRh20tW5orTFIlpy5fockVNGV1t9E1dB8zKfK4ljlTTv6+r7LCyVq0gpk4C3CNmRBre0cyKuptrLiHxR7Qo2vFtlzRfk3cw/VEEIXh2TX84AegIGJbfT4994dBAYNg53fjHeDTvQ08kp/UKjnCQnN3VW9Td41XPWDX88SViADZjtTQ8PsrF14lN9mhj1RYPDWWpKasdYgHrfl3AQuvA4iTRV8ku6uYhQYtmFSf6NbGnTKGtxlwTas0HjW/76uqo2/3EYFKnBHOTsQGXRMq8CCiJ1zK1BSdRxE9bJUUBFsPCijUdOZMXWoQxAD9C4aa35iimV8VUJjmHaDLa3TNpKHTbPLTxXQwk//zloCF0zpjLwut1WPxJmE= arthur@PC_Portable_Art
    networks:
      - jenkins
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  registry:
    image: registry:2
    container_name: private_registry
    ports:
      - "5001:5000"
    volumes:
      - registry_data:/var/lib/registry
    restart: always
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data:
  jenkins-docker-certs:
  final_server_deploy:
  agent_workdir:
  registry_data:
