
services:
  eshopwebmvc:
    image: localhost:5001/eshopwebmvc
    depends_on:
      - "sqlserver"

  eshoppublicapi:
    image: localhost:5001/eshoppublicapi
    depends_on:
      - "sqlserver"
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y